server:
  port: 8082
 
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rating_service
    username: postgres
    password: Stayfocus@12
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  application:
    name: RATING-SERVICE
    
  config:
    import: optional:configserver:http://localhost:8084
    
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:9090/eureka
    